<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Productos</title>
</head>
<body>
    <?php
    if (($_SESSION['user'])) {
        echo "<a href='index.php?c=user&view_user=1'><h1><img width='60px' src= './public/img/profile/".$_SESSION['user']->getImg()."'> Hola " . htmlspecialchars($_SESSION['user']->getUsername()) . "</h1></a><br><br>";
        if (($_SESSION['user']->getRol()==1)) {
            echo "<a href='index.php?c=product&add_product=1'>Registrar Producto</a><br>";
        }
        if($carrito){
            echo "En el carrito tienes " . count($carrito) . " producto distinto";
            echo " | ";
            echo "<a href='index.php?c=purchase&view_purchase=1'>Ver carrito</a>";
        }else{
            echo "En el carrito no tienes productos";
        }
        echo "<br><hr>";
    }else{
        echo "<a href='index.php?c=user&login=1'>Iniciar Sesión</a>";
        echo " | ";
        echo "<a href='index.php?c=user&registro=1'>Registrarse</a>";
        echo "<hr>";
    }
    ?>
    

    <?php
    foreach ($products as $product) {
        $id = $product->getId();
        $name = $product->getName();

        echo "
        <img width='60px' src= './public/img/products/".$product->getImg()."'>
        <h2>
            <a href='index.php?id=$id'>$name</a>
            </h2>
        ";
        if($_SESSION['user']){
            echo "<a href='index.php?c=purchase&add_purchase_line=$id'>Añadir al carrito</a>";
            echo "<br>";
        }
    }
    if($_SESSION['user']){
            echo "<br><a href='?c=user&logout=1'>Cerrar Sesion</a>";
        }
    
    ?>
</body>

</html>